apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nodeapp

images:
- name: ricardocosta94/kga
  newTag: cd413093cb6f4d8cc9f9ecedef8fa578072eb4d5
