apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nodeapp

images:
- name: ricardocosta94/kga
  newName: ricardocosta94/kga
  newTag: latest ## set new tags here